name: VBS_TRAVEL
options:
  bundleIdPrefix: vn.id.kien-developer
targets:
  FlightBookingApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0" # Hỗ trợ từ iOS 15 trở lên
    sources: [Sources]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        # THÊM: khai báo Launch Screen để app chạy full màn hình
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        # THÊM: chỉ hỗ trợ iPhone, hướng dọc
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        # THÊM: dùng AppIcon làm icon app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # THÊM: tên hiển thị dưới icon
        INFOPLIST_KEY_CFBundleDisplayName: "VBS TRAVEL"
        # Bypass chứng chỉ Apple Developer để có thể build thành công file IPA
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO